# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-04 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_reg_attack_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasAttacked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_attacks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_list', to='log_reg_attack_app.User')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defend_list', to='log_reg_attack_app.User')),
            ],
        ),
    ]
